name = "rappel"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_erlang = "~> 0.22"
gleam_otp = "~> 0.7"
glance = "~> 0.7"
gleam_json = "~> 0.6"
simplifile = "~> 0.1"
shellout = "~> 1.4"
gloml = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.10"
